### ISSUE TITLE
ErrorContainer schema minItems needs to be greater than 0 in openapi.yaml 

### ISSUE THREAD

**Issue by lewismc** [tagbase/tagbase-server#254]
The following code block in `openapi.yaml`
```
    ErrorContainer:
      description: 'An error response for an operation.'
      type: object
      properties:
        errors:
          type: array
          minItems: 0
```
... results in SonarCloud reporting the following

> The length of a collection is always ">=0", so update this test to either "==0" or ">0".

This is because the bug is carried through to the autogenerated python-flask code generated by the openapi generator.

The fix is for us to set `minItems` to `1`.
